name: Analysis

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup cvmfs
      # Setup cvmfs filesystem access
      run: ./setup.sh

    - name: Run analysis
      # Run an analysis script
      run: ./run.sh
