name: Analysis

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - id: eic-cvmfs-spack
      uses: actions/eic-cvmfs-spack-action@v1

    - name: Run analysis
      # Run an analysis script
      run: ./run.sh | tee run.log
    - name: Upload log
      uses: actions/upload-artifact@v2
      with:
        name: run.log
        path: run.log
