name: Analysis

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup
      run: ./setup.sh | tee setup.log
    - name: Upload setup log
      uses: actions/upload-artifact@v2
      with:
        name: setup.log
        path: setup.log

    - name: Run
      run: ./run.sh | tee run.log
    - name: Upload run log
      uses: actions/upload-artifact@v2
      with:
        name: run.log
        path: run.log
