name: Cvmfs

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: wdconinc/eic-cvmfs-spack-action@main
      with:
         cvmfs_repositories: 'eic.opensciencegrid.org'
    - name: Setup CernVM-FS
      run: cat /etc/cvmfs/default.local && ls /cvmfs/eic.opensciencegrid.org/ | tee run.log
    - name: Upload run log
      uses: actions/upload-artifact@v2
      with:
        name: run.log
        path: run.log
